### ISSUE TITLE
Crashing on HOS boot for OFW 11.0.1 w/ Atmos 0.16.2

### ISSUE THREAD

**Issue by Shaunathanz** [WerWolv/nx-ovlloader#15]
![Untitled](https://user-images.githubusercontent.com/13986091/103431157-73cba880-4b91-11eb-990f-c361f32f1569.jpg)

Was previously working perfectly fine on HOS 10.2 and Atmosphere 0.15 alongside SaltyNX and sys-con. I've deleted SaltyNX and all other modules yet adding nx-ovlloader to the contents folder leads to a crash at the Switch boot logo 100% of the time. I miss my cheats and OC settings toggles 3':

**Comment by Shaunathanz** [comment]
Things I've tried:

- erasing emuMMC and creating new emuMMC from clean NAND
- Removing all sysmodules
- Updated to atmosphere 0.17.0
- Using older versions of nx-ovlloader
- Removing all .ovl files
- Using older versions of tesla menu ovl
- checked microSD for errors with Disk Utility
- Card has always been fat32 so no need to wipe and reformat
- Erased all files on SD card except those for Hekate and Atmosphere
The setup is Hekate launches Atmosphere (not with fss0 but with fusee-primary) and then usually Atmosphere just loads. Ever since I updated with ChoiDujour and then to the most recent with Daybreak I get a crash on the Nintendo logo with a variation of the error screen pictured above only with nx-ovlloader in the contents folder. Every other piece of homebrew still works. There are no other contents folders with different title IDs with files for older versions of nx-ovlloader.

**Comment by Shaunathanz** [comment]
I'm just going to move on with life

**Comment by ELY3M** [comment]
try using fuse-primary instead of hekate to fire up atmosphere.   I always use fuse-primary to fire up atmosphere.   my tesla overlay always work for me.

**Comment by ELY3M** [comment]
I am on atmosphere 0.17.1 and firmware 11.0.1  right now as this writing at this time.

**Comment by Shaunathanz** [comment]
That's the confusing thing about all this. I'm not booting Atmosphere using fss0 (Hekate). I'm using the payloads menu to boot with fusee-primary.bin. I even went a step further and booted fusee straight from RCM mode to eliminate Hekate as a possibility. I updated HOS to a clean install and made a new emunand just to see if my HOS emuMMC was corrupted somehow, and nothing worked.
