### ISSUE TITLE
Switch won't boot at FW 13.0.0 Atmosphere 1.1.1

### ISSUE THREAD

**Issue by Prantzz** [WerWolv/nx-ovlloader#17]
booting through fusee, after copying nx-ovlloader to the contents folder, it shows atmosphere logo and then the screen goes black and switch won't boot, forcing me to reboot to RCM.

**Comment by KernelGM** [comment]
Same here too. I will like one update for this. Thx WerWolv. 😄

**Comment by pouyaman** [comment]
Might be worth double checking what overlay modules you have installed.  
I have a similar setup (13.0.0 and 1.1.1) and no issues. I had to update edizon to get it working.

Also make sure you have the latest fusee as it was updated for the latest release.
 (refer to atmosphere for details).

Last thing to check is clear out all setting and modules and start from a clean sheet.

**Comment by Prantzz** [comment]
> 
> 
> Might be worth double checking what overlay modules you have installed. I have a similar setup (13.0.0 and 1.1.1) and no issues. I had to update SaltyNX and edizon to get it working. I have 4 overlay modules:
>

Had a bad overlay file - fixed, its all working! 

My bad! - it works great :D
