### ISSUE TITLE
Version issues on 13.2.1

### ISSUE THREAD

**Issue by Flowx3** [WerWolv/nx-ovlloader#19]
V1.0.6 don't work on Firmware 13.2.1 but 1.0.5 does

**Comment by Attect** [comment]
v1.0.6 & v1.0.5 don't work on my switch.
13.2.1|AMS 1.2.6|E

I have been copy nx-ovlloader.zip & ovlmenu.zip (decompress)  files to sdcard root .
But I notice before that, my sdcard doesn't exists atmosphere\contents folder.

**Comment by WerWolv** [comment]
Simply create that folder if it's not there
