### ISSUE TITLE
Pro Controller Compatibility on FW 10.0

### ISSUE THREAD

**Issue by madh77** [WerWolv/nx-ovlloader#2]
Hi, it seems i'm unable to recall the tesla menu on the fly in game from nintendo pro controller, but if I recall the tesla menu from the undocked console the menu appear.
Is an issue?
Thank you so much for your work.

**Comment by masterchan-777** [comment]
Having the exact same issue, I can confirm it's not a Pro Controller issue though, I can recall the tesla menu with the Pro Controller when the console is undocked. Could be a bug that the new loader only detects joystic keys input when the system is undocked (applet mode).

**Comment by TechGeekGamer** [comment]
Tutorial 13 on the EdiZon ⚡️ Tesla server: 
**__13. The Tesla menu doesn't want to appear ingame but blocks input__**
```
This is an issue that started happening in 10.0.0. Go under Settings -> TV Output and make sure that the display scaling is set to 100%. Anything else will cause the menu to not appear anymore in games.
```

**Comment by madh77** [comment]
> I can confirm that adjusting the TO Out display scaling to 100% fixed the issue for me.

Me too. Thank you.
