### ISSUE TITLE
Support for Switch v16.0.0 / Atmosphere v1.5.0

### ISSUE THREAD

**Issue by North-West-Wind** [WerWolv/nx-ovlloader#22]
Atmosphere v1.5.0 + Switch v16.0.0 crashes right after boot if nx-ovlloader is present.

**Comment by shae23** [comment]
I also have this issue on Atmosphere v1.5.0 + Switch v16.0.0 . I had to delete the 420000000007E51A folder to get things working.

**Comment by Hellmuss** [comment]
Same problem, nx ovlloader crash atmosphere v1.5.0 + switch 16.0.0

**Comment by ItzCilos** [comment]
420000000007E51A Folder crashes atmosphere please update ):

**Comment by djskual** [comment]
Same thing for me. Sure you need to fix tesla menu too. Hope you can use the modified libnx for 16.0.0.
You can use Atmosphere's libnx fork and 16.0.0 branch - [https://github.com/Atmosphere-NX/libnx/tree/1600_support](https://github.com/Atmosphere-NX/libnx/tree/1600_support)

**Comment by masagrator** [comment]
You don't need to update ovlloader. You need to update only tesla menu (ovlmenu)

**Comment by djskual** [comment]
ok, i just need to wait the new release of tesla menu?

**Comment by North-West-Wind** [comment]
I saw Tesla-Menu updated their source code, but have not made a release yet.

**Comment by urherenow** [comment]
Either way, this issue is invalid. Please close.

**Comment by ItzCilos** [comment]
> Either way, this issue is invalid. Please close.

yea my bad i didnt know im kinda new to everything and still reading into everything

**Comment by Arch9SK7** [comment]
fix is in tesla.hpp ovl menu 
ASSERT_FATAL(plInitialize(PlServiceType_User)); 
^ fix that and it works on 16

**Comment by masagrator** [comment]
> fix is in tesla.hpp ovl menu ASSERT_FATAL(plInitialize(PlServiceType_User)); ^ fix that and it works on 16

libtesla already has fix implemented. Just pull newest version of libtesla to any repo that is using main repo and compile.
