### ISSUE TITLE
Atmosphere not loading

### ISSUE THREAD

**Issue by Minecraftplayer20** [WerWolv/nx-ovlloader#24]
Error code: 2001-0123 (0xf601)
It says a program named 420000000007E51A
Firmware 16.00 (Atmosphere 1.50-master-356d89244)

An error has occurred

**Comment by Bushido1992** [comment]
update your overlays, thats the issue. ALL overlays MUST be updated to Firmware 16.0. Older not work and crash the Switch

**Comment by Minecraftplayer20** [comment]
> update your overlays, thats the issue. ALL overlays MUST be updated to Firmware 16.0. Older not work and crash the Switch

What is an overlay?

**Comment by TheNitzel** [comment]
> 

Not sure if this was your issue as well but the fix for me was to delete the "contents" folder within the Atmosphere folder on my SD card.  Instructions I read said to do this and I missed it.  Doing it after the fact still got it working again.
