### ISSUE TITLE
Atmosphere 1.5.4 FW 16.0.3 Won't Loading nx-ovlloader v1.0.7!

### ISSUE THREAD

**Issue by Mr-Denni** [WerWolv/nx-ovlloader#28]
My system current version is: 16.0.3|AMS 1.5.3|S
Just recently upgrade from AMS 1.4.0 or 1.4.1 (I forgot)!
After upgrade to 16.0.3|AMS 1.5.3, Atmosphere won't loading previous nx-ovlloader [folder 420000000007E51A] (don't know what version) and just crashed!
After that I tried to upgrade nx-ovlloader to last current version (v1.0.7), but the result was same!
Is there a fix for this?
Should I downgrade my FW/CFW to version that nx-ovlloader v1.0.7 supported?
And what version FW/CFW that nx-ovlloader v1.0.7 last supported (work fine)?
Thanks
![20230801_190104](https://github.com/WerWolv/nx-ovlloader/assets/87647555/68fba712-eec8-48fe-ac60-4bc6049758e7)

**Comment by Mr-Denni** [comment]
> Did you update Tesla Menu to newest version?

First, thanks for offering your solution. 🙏
Yes, after updating "ovlmenu.ovl" file to the last version (v1.2.3), I finally can pass that error & safely entering the HOME Menu.
BUT, when I tried to activate the Tesla Menu inside a game (by pressing a set of buttons), suddenly that error screen came back! 😭
Any other suggestions or solutions, please...

**Comment by masagrator** [comment]
Update other overlays too.

**Comment by Mr-Denni** [comment]
> Update other overlays too.

YES, finally PROBLEM SOLVED! 🥳
The menu operation is rather sluggish than before, but it worked! 👍
Thank you very much! 🙏🙏🙏

**Comment by Mr-Denni** [comment]
> Update other overlays too.

YES, finally PROBLEM SOLVED! 🥳
The menu operation is rather sluggish than before, but it worked! 👍
Thank you very much! 🙏🙏🙏
