### ISSUE TITLE
Nx ovlloader not start FW17.0.1

### ISSUE THREAD

**Issue by Fujin33** [WerWolv/nx-ovlloader#33]
Salut, quand je lance le set de touche L+down+R3 (stick), ovl ne s'affiche pas
Conf : firmware17.0.1 + hekate 6.1.0 + ams 1.6.2
NX ovlloader 1.0.7 + lib tesla 1.2.3 + Edizon overlay 1.0.7 (proferabg)

Hi, when I launch the L+down+R3 key set (stick), ovl is not displayed
Conf: firmware17.0.1 + hekate 6.1.0 + ams 1.6.2
NX ovlloader 1.0.7 + lib tesla 1.2.3 + Edizon overlay 1.0.7 (proferabg)
![Capture d'écran 2024-03-21 155038](https://github.com/WerWolv/nx-ovlloader/assets/111341851/03e54adf-0f08-438e-8c7c-81af625f1fa1)

![Capture d'écran 2024-03-21 155045](https://github.com/WerWolv/nx-ovlloader/assets/111341851/b60891b3-6411-4114-8f63-d9355d0c956f)

![Capture d'écran 2024-03-21 155112](https://github.com/WerWolv/nx-ovlloader/assets/111341851/24cd3c00-eb4f-458c-814d-2645201f3e7e)

![Capture d'écran 2024-03-21 155127](https://github.com/WerWolv/nx-ovlloader/assets/111341851/66d12235-4173-44f5-ae0a-9a1ef20c4192)

![Capture d'écran 2024-03-21 155140](https://github.com/WerWolv/nx-ovlloader/assets/111341851/0dc943ff-8ce5-41fc-9b3a-ed8efa911887)

**Comment by Fujin33** [comment]
I haven't tried it on the dock

**Comment by Fujin33** [comment]
No, nothing happens on the dock either

**Comment by masagrator** [comment]
What you have in `config` folder?

**Comment by Fujin33** [comment]
I have that :

![Capture d'écran 2024-03-21 203421](https://github.com/WerWolv/nx-ovlloader/assets/111341851/11c6ed1b-4a63-4dc4-987b-aa2f37d62b1b)

and if you want :

![Capture d'écran 2024-03-21 203442](https://github.com/WerWolv/nx-ovlloader/assets/111341851/f854d082-dbe5-4ab3-80fd-b1a7d2ac273d)

**Comment by Fujin33** [comment]
Just in case, I just tested my controllers and all the buttons respond well.

**Comment by masagrator** [comment]
Delete config file and restart Switch. Then try again combo.

**Comment by Fujin33** [comment]
Hi, I just renamed "contents" to "contents1" and reinstant and it worked. Afterwards I transferred "contents1" back into "contents" (without overwriting the new folders) and it worked.

**Comment by Fujin33** [comment]
merci ca restera un mystère
