### ISSUE TITLE
Support for 18.1.0 - AMS 1.7.1

### ISSUE THREAD

**Issue by jon-daemon** [WerWolv/nx-ovlloader#36]
I used HATS 1.71.1 which  contains the folder 420000000007E51A and I get a crash  when I start the CFW with error code: 2168-0002 (0x4a8). It's a fresh installation on a new microsd.
If I delete the folder 420000000007E51A, the CFW launches without any errors.
Is this incompatible with firmware 18.1.0 - AMS 1.7.1?

**Comment by Goldenwolfz21** [comment]
i have the same problem and i couldnt figure it out either i think ovlloader or tesla menu needs updating

**Comment by Goldenwolfz21** [comment]
read this 
https://github.com/WerWolv/libtesla/issues/64#issuecomment-1477429891

**Comment by masagrator** [comment]
> read this [WerWolv/libtesla#64 (comment)](https://github.com/WerWolv/libtesla/issues/64#issuecomment-1477429891)

That was fixed in previous year.

**Comment by jon-daemon** [comment]
I found the issue on mine. I use Mac OS  to copy the files on the sd card and  it messes up the archive bit on some files. I had to fix the archive bit using hekate.
