### ISSUE TITLE
1.0.5 Process "Apparently" exiting after loadng Status Monitor Overlay (Mini&Full)

### ISSUE THREAD

**Issue by CaelThunderwing** [WerWolv/nx-ovlloader#4]
Updated to 1.0.5, made sure all overlays are current. and currently using Neutos 0.12.0 
i dont recall somewhat older versions under stock-atmosphere behaving such. Not sure if this is a issue w/ nx-ovlloader, Status Monitor overlay or Neutos Atmospehere fork.  or some combination of the 3.

if theres a way to track whats going on let me know and will update w/ said diagnostic info.

**Comment by TechGeekGamer** [comment]
WerWolv doesn't support Neutos. It may work or may not. If it does, good for you! If it doesn't, 🤷‍♂️.
