### ISSUE TITLE
Tinfoil wont install any package while nx-ovlloader is active.

### ISSUE THREAD

**Issue by jhicken** [WerWolv/nx-ovlloader#5]
When in tinfoil and attempting to install packages I get this error `Invalid PSF0 magic!`

It seems pretty cryptic to me. But maybe you will know more. 

I turned it off by renaming `switch/.overlays` to anything else. Then rebooted. And tinfoil will stop complaining and install packages again.

I'm on the latest Atmosphere and firmware 10.0.1

I'm sorry if this is a Tinfoil issue

**Comment by WerWolv** [comment]
This is a tinfoil issue and piracy is not supported here.

**Comment by jhicken** [comment]
Okay thats what I figured. And I see why you would assume piracy. Since lots of people use tinfoil for that. However my question had absolutely nothing to do with that. 

I have a local nut server with my legally purchased software and title keys on it. I'm just scared to go online because I understand Nintendo has been pretty liberal with the Ban hammer.

In any case thanks for the info. I think blawar is the maintainer of tinfoil and doesn't have a great way to report bugs on tinfoil. So I thought I would ask here just in case you knew of anything in particular that could cause that.

**Comment by deadair3210** [comment]
Unfortunately the patches required to allow nsp and xci installation are mostly used for piracy so they are assumed to be related by default. 

Blawar doesn't really have a way to send issues, not sure it would do any good anyway unfortunately

**Comment by bao3** [comment]
@jhicken It’s not an Overlay issue , you need some patches .But yes , piracy is not supported ....

**Comment by jhicken** [comment]
@bao3 I'm not sure if you read the discussion.  It has something to do with the overlay and tinfoil running at the same time. WerWolv believes it to be a tinfoil issue. I tend to believe him. He has delved much deeper into this type of code than I. And I suspect has a deeper understanding than me.

This is very likely not patch related see the cases below. If you have information to show otherwise feel free to share.

overlays disabled = non functional tinfoil package installs
overlays enabled = funcation tinfoil package installs

Last of all, I already explained the situation with piracy.  Installing packages in tinfoil/goldleaf is not synonymous with piracy. Pointing the finger at people and saying piracy will only make finding and tracking down bugs and issues more difficult. Please stop unless there is a good reason to call it out.

**Comment by WerWolv** [comment]
The dev of Tinfoil has pulled a lot of shit before. It's also possible that he simply blocked Tesla for `<insert reason here>`, wouldn't be the first time he did that. My recommendation is to not use Tinfoil at all but feel free to ask the dev about it, he would know best lol.

The reason I ban discussion of Tinfoil here is because the whole part of the switch's piracy scene is built around Tinfoil which also causes a lot of drama around it I just don't want here. It has a lot of features that make piracy excessively easy. If you're not interested in piracy, you can use Goldleaf just fine and get pretty much the same experience.

**Comment by jhicken** [comment]
Yeah I haven't ever interacted with the tinfoil dev. But from what I have read about him I would not doubt that he broke interaction with Tesla for `(sad sad reasons)`.

Also, I tested with goldleaf as well and it works just fine. So its definitely connected to tinfoil somehow. 

And I respect your reasons for not wanting the discussions around tinfoil here. (I won't bring it up again.)

Thanks for your patience. And really all your awesome work. I'm psyched about all the potential for tesla in the future.
